version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sons_photos
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5431
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/client
      - /client/node_modules
# run this command to create volume: "docker volume create --name=postgres_database"
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.dev
    ports:
      - "5431:5432"
    volumes:
      - postgres_database:/var/lib/postgresql/data:Z
    env_file: ./postgres/postgres.env
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
    depends_on:
      - client
      - api
volumes:
    postgres_database:
        external: true
