version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sons_photos
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5431
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
      - /client/node_modules
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile.dev
    ports:
      - "5431:5432"
    env_file: ./postgres/postgres.env