declare module 'graphql-resolvers' {
        /** Declaration file generated by dts-gen */

    export const skip: any;

    export function all(resolvers: any, ...args: any[]): any;

    export function allResolvers(resolvers: any, ...args: any[]): any;

    export function combine(...args: any[]): any;

    export function combineResolvers(...args: any[]): any;

    export function isDependee(resolver: any, ...args: any[]): any;

    export function pipe(...args: any[]): any;

    export function pipeResolvers(...args: any[]): any;

    export function resolveDependee(dependeeName: any): any;

    export function resolveDependees(dependeeNames: any): any;

    export namespace all {
        const prototype: {
        };

    }

    export namespace allResolvers {
        const prototype: {
        };

    }

    export namespace combine {
        const prototype: {
        };

    }

    export namespace combineResolvers {
        const prototype: {
        };

    }

    export namespace isDependee {
        const prototype: {
        };

    }

    export namespace pipe {
        const prototype: {
        };

    }

    export namespace pipeResolvers {
        const prototype: {
        };

    }

    export namespace resolveDependee {
        const prototype: {
        };

    }

    export namespace resolveDependees {
        const prototype: {
        };

    }
}