\i '/docker-entrypoint-initdb.d/tables/account.sql'
\i '/docker-entrypoint-initdb.d/tables/company.sql'
\i '/docker-entrypoint-initdb.d/tables/contact.sql'
\i '/docker-entrypoint-initdb.d/tables/gallery.sql'
\i '/docker-entrypoint-initdb.d/tables/photo.sql'